nelmio_api_doc:
  documentation:
    components:
      schemas:
        singleTranslation:
          title: "singleTranslation"
          type: "object"
          properties:
            keyword:
              type: "string"
            text:
              type: "string"

        listTranslation:
          title: "listTranslation"
          type: "array"
          items:
            allOf:
              - $ref: '#/components/schemas/singleTranslation'

        deprecateKeyword:
          title: "deprecateKeyword"
          type: "object"
          required: ['keyword']
          properties:
            keyword:
              type: "string"
              example: "keyword"

        keywordCollection:
          title: "keywordCollection"
          type: "array"
          allOf:
            - $ref: '#/components/schemas/deprecateKeyword'

        disablingDate:
          title: "disablingDate"
          type: "object"
          required: ['date']
          properties:
            date:
              type: "datetime"
              example: "2048-05-12"

        putTranslation:
          title: "putTranslation"
          type: "object"
          required: ['keyword', 'text', 'locale', 'domain']
          properties:
            keyword:
              type: "string"
            text:
              type: "string"
            locale:
              type: "string"
            domain:
              type: "string"
              example: "messages"

        postTranslation:
          title: "postTranslation"
          type: "object"
          required: ['keyword', 'text', 'locale']
          properties:
            keyword:
              type: "string"
            text:
              type: "string"
            locale:
              type: "string"

        postTranslations:
          title: "postTranslations"
          type: "array"
          items:
            allOf:
              - $ref: '#/components/schemas/postTranslation'
